config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :recipes, only: [:show, :new, :create, :edit, :update] do
    member do
      post 'favorite'
    end

    collection do
      get 'busca'
    end
  end
  resources :cuisines, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def show
    @cuisine = Cuisine.find(params[:id])
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(params.require(:cuisine).permit(:name))
    if @cuisine.save
      redirect_to @cuisine
    else
      flash.now[:error] = 'Você deve informar o nome da cozinha'
      render 'new'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @recipes = Recipe.all
    @cuisines = Cuisine.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update]
  before_action :set_cuisines, only: [:new, :edit]

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      set_cuisines
      flash.now[:error] = 'Não foi possível salvar sua receita'
      render :new
    end
  end

  def edit
  end

  def update
    @recipe.update(recipe_params())

    flash[:success] = 'Sua receita foi atualizada com sucesso'
    redirect_to @recipe
  end

  def search
    search_term = "%#{params[:q]}%"
    @results = Recipe.where('title LIKE ? or ingredients LIKE ?', search_term, search_term)
    flash.now[:alert] = "Nenhuma receita encontrada" unless @results.any?
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title,
                                   :recipe_type, :cuisine_id, :difficulty,
                                   :cook_time, :ingredients, :method)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_cuisines
    @cuisines = Cuisine.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/new.html.erb
<% if flash[:error] %>
  <%= flash[:error] %>
<% end %>
<ul>
<% @cuisine.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>

<%= form_for(@cuisine) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar'  %>
<% end %>

app/views/cuisines/show.html.erb
<h1>Cozinha <%= @cuisine.name %></h1>

<% if @cuisine.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de cozinha</p>
<% end %>
<% @cuisine.recipes.each do |recipe| %>
  <h1><%= link_to(recipe.title, recipe) %></h1>
  <ul>
    <li><%= recipe.recipe_type %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

app/views/home/index.html.erb
<h1>CookBook</h1>
<p><%= I18n.translate('site_description') %></p>
<%= I18n.localize(Time.zone.now) %>
<%= link_to 'Enviar uma receita', new_recipe_path %>

<% @recipes.each do |r| %>
  <%= render r %>
<% end %>

<% content_for :aside do %>
  <h1>Cozinhas</h1>
  <ul>
  <% @cuisines.each do |cuisine| %>
    <li><%= link_to cuisine.name, cuisine %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Cookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <span>Bem-vindo <%= current_user.email %></span>
      <% else %>
        <%= link_to 'Entrar', new_user_session_path %>
      <% end %>
    </nav>
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <aside>
      <%= yield :aside %>
    </aside>
  </body>
</html>

app/views/recipes/_recipe.html.erb
<h1><%= link_to(recipe.title, recipe) %></h1>
<ul>
  <li><%= recipe.recipe_type %></li>
  <li><%= recipe.cuisine.name %></li>
  <li><%= recipe.difficulty %></li>
  <li><%= recipe.cook_time %> minutos</li>
</ul>

app/views/recipes/edit.html.erb
<%= form_for(@recipe) do |f| %>
  <div>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :recipe_type, 'Tipo da Receita' %>
    <%= f.text_field :recipe_type %>
  </div>
  <div>
    <%= f.label :cuisine_id  %>
    <%= f.collection_select :cuisine_id, @cuisines, :id, :name  %>
  </div>
  <div>
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.text_field :difficulty %>
  </div>
  <div>
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.text_field :cook_time %>
  </div>
  <div>
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_area :ingredients %>
  </div>
  <div>
    <%= f.label :method, 'Como Preparar' %>
    <%= f.text_area :method %>
  </div>
  <%= f.submit 'Atualizar' %>
<% end %>

app/views/recipes/new.html.erb
<h1>Nova Receita</h1>
<% if flash[:error] %>
  <div class="error">
    <%= flash[:error] %>
    <% @recipe.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  </div>
<% end %>
<%= form_for(@recipe) do |f| %>
  <div>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :recipe_type, 'Tipo da Receita' %>
    <%= f.text_field :recipe_type %>
  </div>
  <div>
    <%= f.label :cuisine_id  %>
    <%= f.collection_select :cuisine_id, @cuisines, :id, :name  %>
  </div>
  <div>
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.text_field :difficulty %>
  </div>
  <div>
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.text_field :cook_time %>
  </div>
  <div>
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_area :ingredients %>
  </div>
  <div>
    <%= f.label :method, 'Como Preparar' %>
    <%= f.text_area :method %>
  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/recipes/show.html.erb
<%= flash[:success] %>
<h1><%= @recipe.title %></h1>
<h3>Detalhes</h3>
<p>
  Tipo: <%= @recipe.recipe_type %><br>
  Cozinha: <%= @recipe.cuisine.name %><br>
  Dificuldade: <%= @recipe.difficulty %><br>
  Tempo de preparo: <%= @recipe.cook_time %> minutos<br>
</p>
<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %>
<h3>Como Preparar</h3>
<p><%= @recipe.method %>
<%= link_to 'Editar', edit_recipe_path %>
<%= link_to 'Voltar', root_path %>